version: '3'
services:
    frontend:
        build:
            context: ./todo-frontend
            dockerfile: dev.Dockerfile
        volumes:
            - "./todo-frontend:/usr/src/app"
        ports:
            - "8080:8080"
        environment:
            - VUE_APP_API_URL="Hello"
        depends_on:
            - backend
            - database
    backend:
        build:
            context: ./todo-backend
            dockerfile: dev.Dockerfile
        ports:
            - "8081:8081"
        volumes:
            - "./todo-backend:/app"
        depends_on:
            - database
    database:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=ToDos
            - MONGO_INITDB_ROOT_USERNAME=piotr
            - MONGO_INITDB_ROOT_PASSWORD=piotr1234
        volumes:
            - todomongodata:/data/db
        ports:
            - '27017-27019:27017-27019'
volumes:
    todomongodata:
